### ISSUE TITLE
Error when not specifying email on login

### ISSUE THREAD

**Issue by danteissaias** [notepad/notepad#2]
```
Error: WHERE parameter "email" has invalid "undefined" value
    at SQLiteQueryGenerator.whereItemQuery (/Users/dante/Repos/notepad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2168:13)
    at /Users/dante/Repos/notepad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2157:25
    at Array.forEach (<anonymous>)
    at SQLiteQueryGenerator.whereItemsQuery (/Users/dante/Repos/notepad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2155:35)
    at SQLiteQueryGenerator.getWhereConditions (/Users/dante/Repos/notepad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2567:19)
    at SQLiteQueryGenerator.selectQuery (/Users/dante/Repos/notepad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1322:28)
    at QueryInterface.select (/Users/dante/Repos/notepad/node_modules/sequelize/lib/query-interface.js:1119:27)
    at /Users/dante/Repos/notepad/node_modules/sequelize/lib/model.js:1756:34
    at processImmediate (internal/timers.js:439:21)
```

**Comment by danteissaias** [comment]
This can easily be fixed by validating the request body
